apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "shippingservice"
  description: "Shipping Services Api"
spec:
  type: graphql
  lifecycle: production
  owner:  "platform-dx-organization"
  apiProvidedBy:
    -'microservices-demo'
  definition: |
    schema {
      query: Query
      mutation: Mutation
    }
    type Query {
      getBook(id: ID!): Book
    }
    type Mutation {
      createBook(book: BookInput!): Book
      updateBook(id: ID!, book: BookInput!): Book
      deleteBook(id: ID!): Boolean
    }
    input BookInput {
      title: String!
      author: String!
    }
    type Book {
      id: ID!
      title: String!
      author: String!
    }