apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "microservices-demo"
  description: "example of microservices relationship"
  links:
    - url: https://github.com/GoogleCloudPlatform/microservices-demo
      title: GoogleCloudPlatform | microservices-demo
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug:  platform-dx-organization/microservices-demo
    sonarqube.org/project-key: "microservices-demo"
    backstage.io/kubernetes-label-selector: "app=microservices-demo"
    backstage.io/adr-location: docs/adrs/
spec:
  type: system
  lifecycle: production
  owner: "online-boutique-corp"
  providesApis:
    - "adservice"
    - "cartservice"
    - "checkoutservice"
    - "currencyservice"
    - "emailservice"
    - "paymentservice"
    - "productcatalogservice"
    - "recommendationservice"
    - "shippingservice"
