site_name: Online Boutique
site_description: Some description

nav:
  - Home: 'index.md'
  - 'Tutotials':
    - 'Cloundshell Tutorial': cloudshell-tutorial.md
    - 'Deploy Stack': deploystack.md
    - 'Development Guide': development-guide.md 
    - 'Product Requirements': product-requirements.md
    - 'Purpose': purpose.md
  - 'Advertising Service': adservice.md
  - 'Checkout Service': checkoutservice.md
  - 'Product Catalog Service': productcatalogservice.md
  - 'Shipping Service': shippingservice.md

theme:
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
    - navigation.path

plugins:
  - techdocs-core
  - search