site_name: Online Boutique
site_description: Some description

nav:
  - Home: 'index.md'
  - 'Tutotials':
    - 'Cloundshell Tutorial': cloundshell-tutorial.md
    - 'Deploy Stack': deploystack.md
    - 'Development Guide': development-guide.md 
    - 'Product Requirements': product-requirements.md
    - 'Purpose': purpose.md
  - 'Advertising Service': adservice.md
  - 'Checkout Service': checkoutservice.md
  - 'Product Catalog Service': productcatalogservice.md
  - 'Shipping Service': shippingservice.md

plugins:
  - techdocs-core
  - search