apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "cartservice"
  description: "Cart Services Api"
  tags:
    - oas2
spec:
  type: openapi
  lifecycle: production
  owner:  "online-boutique-corp"
  apiProvidedBy:
    -'microservices-demo'
  definition: |
    swagger: '2.0'
    info:
      title: art Services Api
      version: 1.0.0
    paths:
      /pets:
        get:
          responses:
            '200':
              description: A list of pets
        post:
          responses:
            '201':
              description: A new pet is created
        put:
          responses:
            '200':
              description: The pet is updated
        delete:
          responses:
            '204':
              description: The pet is deleted