apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "productcatalogservice"
  description: "Product Catalog Services Api"
  tags:
    - async
spec:
  type: asyncapi
  lifecycle: production
  owner:  "online-boutique-corp"
  apiProvidedBy:
    -'microservices-demo'
  definition: |
    asyncapi: '2.0.0'
    info: 
      title: Product Catalog Services Api
      version: '1.0.0' 
    channels:
      light/measured:
        subscribe:
          message:
            payload:
              type: object
      light/changed:
        publish:
          message:
            payload:
              type: object